### ISSUE TITLE
compile error: multi-character literals are not allowed in lexer sets

### ISSUE THREAD

**Issue by hlolli** [oracle/fastr#69] opened 2019-04-14 01:25 UTC
From this line https://github.com/oracle/fastr/blob/498b309fa1966a2d4163a9e7c49a162dedc4d4a0/com.oracle.truffle.r.parser/src/com/oracle/truffle/r/parser/R.g#L957 I get `multi-character literals are not allowed in lexer sets: '??'` when compiling fastr 1.0.0-rc15. I fixed it with a sed operation where I delete `"'α'..'ω'|'Α'..'Ω'|"`. I don't have the exact line:column anymore after my fix, but it was pointing at these greek letters.

**Comment by steve-s** [comment] 2019-04-15 13:39
Hello Hlöðver,

thank you for reporting this. We haven't seen this issue before and cannot reproduce. However, it is true that we should have some more robust solution than lexer sets. Can you try the following patch?

```
diff --git a/com.oracle.truffle.r.parser/src/com/oracle/truffle/r/parser/R.g b/com.oracle.truffle.r.parser/src/com/oracle/truffle/r/parser/R.g
index 5dda25a39d..766cd3f1d8 100644
--- a/com.oracle.truffle.r.parser/src/com/oracle/truffle/r/parser/R.g
+++ b/com.oracle.truffle.r.parser/src/com/oracle/truffle/r/parser/R.g
@@ -954,7 +954,7 @@ fragment OP_NAME
     | ('*'|'/'|'+'|'-'|'>'|'<'|'='|'|'|'&'|':'|'^'|'.'|'~'|','|'?')
     ;
 
-fragment ID_NAME : ('a'..'z'|'A'..'Z'|'α'..'ω'|'Α'..'Ω'|'_') ('a'..'z'|'A'..'Z'|'0'..'9'|'α'..'ω'|'Α'..'Ω'|'_'|'.')* ;
+fragment ID_NAME : [\p{Alpha}_] [\p{Alnum}_.]* ;
 
 fragment ESC_SEQ
     : '\\' ('b'|'t'|'n'|'f'|'r'|'"'|'\''|'`'|'\\'|' '|'a'|'v')
```

**Comment by steve-s** [comment] 2019-04-16 16:56
Should be fixed, please re-open if the problem persists.

**Closed by steve-s** 2019-04-16 16:56 UTC

**Comment by hlolli** [comment] 2019-04-16 17:06
ok, I won't have time to test until 1,5 week. Will report!
