### ISSUE TITLE
Cannot install RcppParallel

### ISSUE THREAD

**Issue by comicfans** [oracle/fastr#52] opened 2019-01-23 09:37 UTC
I'm using graal/fastr 1.0.0 rc11

<pre>

install.packages('RcppParallel')

Installing package into ‘/b/b/e/fastr/library’
(as ‘lib’ is unspecified)
Content type 'application/octet-stream' length 1265021 bytes (1.2 MB)
* installing *source* package ‘RcppParallel’ ...
** package ‘RcppParallel’ successfully unpacked and MD5 sums checked
* preparing to configure package 'RcppParallel' ...
** executing 'R CMD config'
** executing 'R CMD config'
An internal error occurred.
Please report an issue at https://github.com/oracle/fastr including the commands. You can rerun FastR with --jvm.DR:+PrintErrorStacktracesToFile to turn on internal errors logging. Please attach the log file
 to the issue if possible.
ERROR: configuration failed for package ‘RcppParallel’
* removing ‘/b/b/e/fastr/library/RcppParallel’

</pre>

**Comment by steve-s** [comment] 2019-01-23 22:38
Hi comicfans, 

thank you for the report. We can reproduce the issue. It's a bug in the `gsub` builtin. We're working on a fix.

**Comment by steve-s** [comment] 2019-02-21 08:26
Should be fixed in d25a713b8b3ff479940233177213145a623ca64e and `RcppParallel` can be now installed on FastR. I've also tried the [matrix transform example](http://gallery.rcpp.org/articles/parallel-matrix-transform/) and it seems to be working fine.

**Closed by steve-s** 2019-02-21 08:26 UTC
Labels: bug
