### ISSUE TITLE
Crash with "Code installation failed: code is too large"

### ISSUE THREAD

**Issue by ceresek** [oracle/fastr#125] opened 2019-11-29 15:36 UTC
When running some of our computations on the FastR cluster, I have workers crashing with the following message:

```
[truffle] opt fail         isTRUE                                                      |Reason jdk.vm.ci.code.BailoutException: Code installation failed: code is too large 
jdk.vm.ci.code.BailoutException: Code installation failed: code is too large
	at jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:150)
	at org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:194)
	at org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:147)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compilePEGraph(TruffleCompilerImpl.java:534)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:455)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:637)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:579)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:178)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:280)
	at org.graalvm.compiler.truffle.compiler.hotspot.libgraal.HotSpotToSVMEntryPoints.doCompile(HotSpotToSVMEntryPoints.java:253)

Error in if (n <= Nbound[kmin - 1]) BB <- TRUE else BB <- FALSE : 
  argument is of length zero
```

Any suggestions how to fix this ? (The computation used the installation of GraalVM created with `installFastR()`.)

**Comment by mukel** [comment] 2019-11-30 16:11
This is not specific to FastR, but a weakness of the Truffle inliner, which is based on AST sizes, which are not a representative measure of the size of the compiled code, my understanding is that some FastR nodes are very "fat" but still are counted as 1.

There's a language agnostic inliner in the works, but it's not ready yet.
In the meantime, try reducing the inliner budget e.g. `-Dgraal.TruffleInliningMaxCallerSize=800` (default is 2250) and/or bumping the code cache `-XX:ReservedCodeCacheSize=512m`.

**Comment by steve-s** [comment] 2019-12-01 14:41
Alfonso correctly describes why this happens in FastR. However, this should not be a fatal issue just a performance issue. The behavior can be controlled by [`-Dgraal.CompilationFailureAction` option](https://www.graalvm.org/docs/reference-manual/languages/jvm/) and I thought that by default this should be set to "silent".

**Comment by steve-s** [comment] 2019-12-01 14:46
Ah, the actual issue will be just this part of the message:
```
Error in if (n <= Nbound[kmin - 1]) BB <- TRUE else BB <- FALSE : 
  argument is of length zero
```
and that looks like an R level issue. Potentially some incompatibility of FastR vs GNU-R or some variable that is not available at the worker node?

**Comment by ceresek** [comment] 2019-12-02 08:48
Got it, thanks ! Turned out to be a coincidence which made both error messages appear one after the other with no intervening output. I've fixed the R issue, and extended the code cache size just to avoid potential performance loss (I take it there is no significant negative impact with large code cache size, except for it eating up some memory ?).

**Comment by steve-s** [comment] 2019-12-09 15:01
Hi Petr, 

we shouldn't be printing the "Code installation failed: code is too large" message and the stack trace by default anyway. Did you pass any additional options to FastR or is this default behavior?

**Comment by ceresek** [comment] 2019-12-09 15:05
In this case, the only options passed were `--vm.Xmx32G` and `--R.PrintErrorStacktracesToFile=true` (and possibly whatever other options `fastRCluster` adds to that internally).

BTW I've since added `--vm.XX:ReservedCodeCacheSize=1G` but saw the same message again. I did not investigate further, can try if this sounds interesting.

**Comment by steve-s** [comment] 2019-12-11 09:26
Thank you for confirming that. In the meantime we managed to reproduce this and it is indeed a bug that we print this message by default (i.e., when no flags/options are passed) -- that's however a different bug than what this issue reported, so I think we can now close it.

**Closed by steve-s** 2019-12-11 09:26 UTC
